apiVersion: k8s.fabkli.ch/v1
kind: Fdeployment
metadata:
  name: backend
spec:
  path: "/api"
  replicas: 1
  port: 8000
  tag: "latest"
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 128Mi
  healthCheck:
    livenessProbe:
      path: "/"
    readinessProbe:
      path: "/"
  host: "fabkli.ch"
  env:
    - name: GIN_MODE
      value: release