basePath: /api
definitions:
  company.Company:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  person.Person:
    properties:
      age:
        type: integer
      company:
        type: string
      name:
        type: string
    type: object
  person.PersonPost:
    properties:
      age:
        type: integer
      companyId:
        type: integer
      name:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Example API for demonstrating how to use Swagger with Gin and its folder
    structure.
  title: Go Example API
  version: "1.0"
paths:
  /companies:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/company.Company'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all companies
      tags:
      - companies
    post:
      consumes:
      - application/json
      parameters:
      - description: Company
        in: body
        name: company
        required: true
        schema:
          $ref: '#/definitions/company.Company'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Post a company
      tags:
      - companies
  /persons:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/person.Person'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all persons
      tags:
      - persons
    post:
      consumes:
      - application/json
      parameters:
      - description: Person
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/person.PersonPost'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Post a person
      tags:
      - persons
swagger: "2.0"
